#!/usr/bin/env ruby

require 'tempfile'
require_relative 'graytext'

command = ARGV.shift
if command == 'upload'
  Graytext::upload
elsif command == 'code'
  Graytext::incode
else
  puts Graytext::interpret(ARGV[0], ARGV[1])[0]
end
