#!/usr/bin/env ruby

require File.expand_path('~/checkouts/oauthor-ruby/oauthor')
require_relative 'graytext'

def publish(gray, html, config, oauthor)
  if config.has_key?('title')

    categories = oauthor.get_paginated('https://twodee.org/blog/wp-json/wp/v2/categories', {
      per_page: 100,
    })
    slug2id = categories.map { |category| [category[:slug], category[:id]] }.to_h

    if config.has_key?('categories')
      categories = config['categories'].split(/,/).map do |slug|
        slug2id[slug]
      end
    else
      categories = []
    end

    parameters = {
      title: config['title'],
      content: html,
      status: config.has_key?('status') ? config['status'] : 'publish',
      categories: categories
    }

    if config.has_key?('release')
      if config['release'] =~ %r{(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)}
        parameters['date'] = config['release']
      else
        STDERR.puts "Bad release time: #{config['release']}"
        exit 1
      end
    end

    url = 'https://twodee.org/blog/wp-json/wp/v2/posts'
    if config.has_key?('pid')
      parameters['id'] = config['pid']
      url += "/#{config['pid']}"
    end

    response = oauthor.post_json(url, parameters)

    if !config.has_key?('pid')
      publish = JSON.parse(response.body)
      publish['link'] =~ /(\d+)$/
      id = $1

      newGray = gray + '.new'
      File.open(newGray, 'w') do |f|
        f.puts "[let pid=\"#{id}\"]"
        File.foreach(gray) do |line|
          f.puts line
        end
      end

      File.rename(newGray, gray)
    end
  else
    STDERR.puts "I need a title."
  end
end

oauthor = Oauthor.new(File.expand_path('~/.oauthor/wordpress-blog.json'), 4000)
ARGV.each do |gray|
  html, config = Graytext::interpret('wordpress', gray)
  publish(gray, html, config, oauthor)
end
