#!/usr/bin/env ruby

require 'net/http'

def port_open?(port)
  !system("lsof -i:#{port}", out: '/dev/null')
end

if port_open? 4567
  pid = Process.fork
  if pid.nil?
    require 'sinatra'

    $stderr.reopen(File.new('/dev/null', 'w'))
    $stdout.reopen(File.new('/dev/null', 'w'))
    $path = nil

    get %r{/(.+)} do |file|
      send_file file
    end

    get '/' do
      if $path
        `gray generate html #{$path}`
      else
        'n/a'
      end
    end

    put %r{(/.*)} do |file|
      $path = file
      puts "now serving #{$path}"
      Dir.chdir(File.dirname($path))
      $path = File.basename($path)
    end
  else
    # Let parent process release child.
    while port_open? 4567
      sleep(1)
    end
    Process.detach(pid)
    if ARGV.size > 0
      path = ARGV[0]
      http = Net::HTTP.new('0.0.0.0', 4567)
      response = http.send_request('PUT', File.absolute_path(path), '')
    end
  end
end

